<?php

use CashRegister\core\database\DBConnection;

class m0007_products {

    public function up(): void {
        $db = DBConnection::getInstance();
        $query = "INSERT INTO products (productsName, productsDescription, productsPrice, productsAvailable, productsImagePath, tvaID, stockID) VALUES 
            ('GTT Communications, Inc.', 'aliquam convallis', 1.97, false, 'Luctus.xls', 2, 6),
            ('Akamai Technologies, Inc.', 'nulla ultrices aliquet maecenas leo', 3.64, false, 'Nunc.mp3', 3, 94),
            ('FactSet Research Systems Inc.', 'nisl duis', 11.62, true, 'NullaNeque.avi', 2, 55),
            ('Telephone and Data Systems, Inc.', 'in felis donec semper sapien', 1.27, false, 'NislAeneanLectus.png', 3, 90),
            ('Centene Corporation', 'est', 14.23, true, 'At.pdf', 1, 78),
            ('Cigna Corporation', 'ultrices', 5.45, false, 'FelisFusce.ppt', 3, 13),
            ('Great Plains Energy Inc', 'tortor', 2.25, true, 'EratEros.xls', 3, 75),
            ('Textron Inc.', 'augue aliquam erat', 11.68, false, 'PlaceratAnteNulla.avi', 1, 23),
            ('Sharps Compliance Corp', 'blandit nam nulla integer', 5.31, false, 'ConsequatMetus.pdf', 2, 58),
            ('Calamos Convertible Opportunities', 'interdum mauris non', 7.69, false, 'NullamPorttitor.mov', 1, 46),
            ('Great Elm Capital Corp.', 'mauris eget massa tempor', 2.07, true, 'LectusSuspendisse.png', 3, 48),
            ('Lion Biotechnologies, Inc.', 'nam nulla', 5.96, false, 'Velit.doc', 2, 91),
            ('Sanofi', 'libero nullam sit amet', 3.76, false, 'EnimLoremIpsum.tiff', 3, 94),
            ('J.B. Hunt Transport Services, Inc.', 'platea dictumst morbi vestibulum', 8.33, true, 'CrasPellentesque.txt', 3, 56),
            ('Xylem Inc.', 'quisque arcu libero', 9.1, true, 'PedeUllamcorperAugue.png', 2, 76),
            ('Fulgent Genetics, Inc.', 'lorem id', 8.19, false, 'DiamNamTristique.gif', 2, 56),
            ('Hannon Armstrong Sustainable, Inc.', 'vestibulum', 12.86, true, 'BlanditNonInterdum.tiff', 1, 94),
            ('D.R. Horton, Inc.', 'fusce', 6.27, false, 'Sapien.png', 3, 48),
            ('Meridian Bancorp, Inc.', 'lorem', 10.96, true, 'Auctor.jpeg', 1, 93),
            ('Annaly Capital Management Inc', 'luctus cum sociis', 9.33, true, 'Dolor.mp3', 3, 4),
            ('Carbo Ceramics, Inc.', 'nunc vestibulum', 5.03, true, 'NequeVestibulum.mp3', 1, 21),
            ('STARWOOD PROPERTY TRUST, INC.', 'sociis natoque', 14.3, false, 'Diam.txt', 1, 58),
            ('Aevi Genomic Medicine, Inc.', 'amet sem', 9.46, false, 'Volutpat.mp3', 2, 90),
            ('Flowserve Corporation', 'vel', 11.41, true, 'RisusSemperPorta.png', 2, 35),
            ('AlphaMark Actively Managed Small Cap ETF', 'sit amet cursus id turpis', 2.09, false, 'NullaAcEnim.mpeg', 3, 70),
            ('Statoil ASA', 'vestibulum sed magna at nunc', 8.34, true, 'Primis.ppt', 2, 75),
            ('INVESCO MORTGAGE CAPITAL INC', 'felis sed', 8.82, true, 'MorbiPorttitor.xls', 2, 28),
            ('Nuveen AMT-Free Municipal Credit Income Fund', 'dapibus nulla suscipit ligula in', 7.64, true, 'MattisEgestasMetus.pdf', 3, 11),
            ('Callidus Software, Inc.', 'non velit donec', 4.11, true, 'CrasInPurus.png', 1, 13),
            ('Peabody Energy Corporation', 'duis faucibus', 3.51, true, 'ArcuAdipiscingMolestie.mp3', 1, 55),
            ('Avista Corporation', 'curae donec pharetra', 11.78, true, 'ViverraDapibus.ppt', 3, 44),
            ('JA Solar Holdings, Co., Ltd.', 'integer', 13.11, false, 'IntegerAliquet.mpeg', 3, 75),
            ('Duluth Holdings Inc.', 'turpis', 6.16, true, 'OdioElementum.png', 3, 90),
            ('Strattec Security Corporation', 'sapien', 1.32, true, 'LaoreetUt.mp3', 2, 70),
            ('Navient Corporation', 'pretium quis lectus suspendisse', 1.92, true, 'Primis.mp3', 3, 57),
            ('Mattel, Inc.', 'posuere felis sed', 8.51, true, 'CongueEtiamJusto.mpeg', 2, 34),
            ('National General Holdings Corp', 'natoque penatibus et magnis', 8.96, false, 'LacusAt.ppt', 3, 30),
            ('Shenandoah Telecommunications Co', 'convallis duis consequat', 1.25, true, 'BlanditLacinia.txt', 2, 48),
            ('Blackrock MuniYield Michigan Quality Fund, Inc.', 'amet consectetuer adipiscing elit', 2.39, true, 'IntegerAcNeque.xls', 1, 40),
            ('ENSCO plc', 'luctus ultricies', 13.76, true, 'VulputateElementum.avi', 2, 6),
            ('Universal Technical Institute Inc', 'in quam fringilla rhoncus', 11.65, false, 'NasceturRidiculus.mp3', 3, 51),
            ('Scorpio Tankers Inc.', 'sed magna at nunc', 6.94, false, 'NonVelitDonec.xls', 2, 37),
            ('Dimension Therapeutics, Inc.', 'odio condimentum', 4.27, true, 'EtTempusSemper.ppt', 3, 95),
            ('Kelly Services, Inc.', 'vitae mattis', 1.19, false, 'MorbiQuisTortor.doc', 2, 6),
            ('Global X Yieldco Index ETF', 'donec posuere metus vitae', 11.7, true, 'Tempus.jpeg', 2, 60),
            ('Bright Scholar Education Holdings Limited', 'pretium nisl ut', 6.44, false, 'Praesent.tiff', 3, 97),
            ('TTM Technologies, Inc.', 'placerat ante nulla justo', 12.76, true, 'Habitasse.mp3', 3, 5),
            ('Coach, Inc.', 'nulla sed accumsan felis', 12.23, false, 'Faucibus.xls', 1, 54),
            ('Vanguard Total International Bond ETF', 'blandit non interdum in ante', 4.67, false, 'AtLorem.xls', 2, 26),
            ('Adtalem Global Education Inc.', 'platea dictumst morbi', 11.65, true, 'Nam.gif', 2, 37),
            ('SeaWorld Entertainment, Inc.', 'scelerisque', 13.66, true, 'IntegerPede.ppt', 2, 34),
            ('Stone Energy Corporation', 'rhoncus dui vel sem sed', 9.65, true, 'VelLectus.mp3', 1, 6),
            ('First Trust Rising Dividend Achievers ETF', 'amet diam in', 13.31, true, 'AmetErat.mov', 3, 63),
            ('Western Asset High Income Opportunity Fund, Inc.', 'cum sociis natoque', 13.49, false, 'UtNuncVestibulum.avi', 2, 7),
            ('Principal Real Estate Income Fund', 'nulla eget eros elementum pellentesque', 5.3, true, 'AliquamAugue.tiff', 2, 65),
            ('DTE Energy Company', 'odio', 11.0, true, 'MaurisNon.gif', 3, 15),
            ('Pacific Premier Bancorp Inc', 'ligula', 14.65, true, 'VolutpatConvallisMorbi.xls', 3, 45),
            ('News Corporation', 'tincidunt lacus', 14.11, true, 'Mi.avi', 2, 70),
            ('G. Willi-Food International,  Ltd.', 'ultricies eu nibh quisque id', 4.64, true, 'TinciduntAnteVel.doc', 1, 18),
            ('Global Indemnity Limited', 'eget elit sodales', 1.12, true, 'ElementumPellentesque.avi', 3, 83),
            ('Frontline Ltd.', 'sapien', 3.85, true, 'Lectus.mp3', 3, 84),
            ('Applied Optoelectronics, Inc.', 'mattis nibh ligula nec', 8.78, true, 'TortorIdNulla.xls', 3, 49),
            ('Insperity, Inc.', 'aliquam sit amet diam', 5.33, true, 'InHacHabitasse.avi', 2, 88),
            ('Office Depot, Inc.', 'ante ipsum primis in faucibus', 6.92, true, 'InSapien.mp3', 1, 22),
            ('China Eastern Airlines Corporation Ltd.', 'integer', 7.43, true, 'IntegerANibh.ppt', 3, 63),
            ('Tata Motors Ltd', 'augue vestibulum ante', 4.23, true, 'MorbiNon.ppt', 1, 79),
            ('Astec Industries, Inc.', 'nulla facilisi', 5.69, true, 'Integer.gif', 2, 98),
            ('Addus HomeCare Corporation', 'elementum eu', 8.91, false, 'QuamSollicitudinVitae.doc', 1, 25),
            ('Pacific Gas & Electric Co.', 'enim', 9.35, true, 'BlanditUltrices.mp3', 1, 14),
            ('Globant S.A.', 'hac habitasse', 5.03, true, 'At.doc', 3, 24),
            ('General Electric Company', 'amet turpis elementum ligula', 8.72, false, 'DictumstMaecenasUt.ppt', 2, 9),
            ('PartnerRe Ltd.', 'et ultrices posuere cubilia', 12.38, false, 'PosuereNonummyInteger.png', 3, 1),
            ('LivaNova PLC', 'odio justo sollicitudin ut', 7.58, false, 'In.mp3', 1, 13),
            ('Callon Petroleum Company', 'habitasse', 7.7, true, 'Odio.txt', 1, 92),
            ('Elbit Systems Ltd.', 'cubilia curae', 8.29, false, 'SuscipitAFeugiat.txt', 2, 27),
            ('Synchronoss Technologies, Inc.', 'sem fusce consequat nulla nisl', 8.71, true, 'BlanditNonInterdum.avi', 2, 45),
            ('First Financial Northwest, Inc.', 'erat curabitur gravida', 13.91, false, 'Aliquet.png', 1, 89),
            ('Bio-Techne Corp', 'euismod scelerisque quam turpis', 8.74, true, 'Eget.jpeg', 1, 78),
            ('Lantronix, Inc.', 'luctus', 4.91, false, 'VolutpatQuam.tiff', 3, 52),
            ('Sify Technologies Limited', 'ante nulla justo aliquam quis', 7.1, true, 'VariusUtBlandit.pdf', 2, 4),
            ('Legg Mason, Inc.', 'cum', 1.17, false, 'NibhInLectus.pdf', 3, 26),
            ('First Trust Small Cap Core AlphaDEX Fund', 'vulputate elementum nullam varius', 13.0, false, 'Sed.xls', 1, 23),
            ('AGNC Investment Corp.', 'pulvinar lobortis est phasellus', 10.23, false, 'ElementumInHac.ppt', 2, 83),
            ('First Trust Senior Floating Rate 2022', 'dui vel nisl', 13.59, false, 'TinciduntAnteVel.gif', 2, 72),
            ('Nova Lifestyle, Inc', 'duis bibendum felis sed', 5.81, false, 'SuspendissePotenti.doc', 2, 49),
            ('Farmers National Banc Corp.', 'eu orci mauris lacinia sapien', 14.56, true, 'RutrumRutrumNeque.avi', 2, 8),
            ('Sigma Designs, Inc.', 'sapien', 5.55, true, 'CuraeNullaDapibus.xls', 1, 46),
            ('Cincinnati Financial Corporation', 'turpis enim blandit mi', 11.38, true, 'Ipsum.xls', 2, 63),
            ('JM Global Holding Company', 'est quam pharetra magna', 6.48, true, 'Et.avi', 3, 36),
            ('Western Refining Logistics, LP', 'sem', 14.16, true, 'Elit.tiff', 3, 54),
            ('Professional Diversity Network, Inc.', 'sapien iaculis congue vivamus', 13.03, false, 'VelitEu.ppt', 3, 66),
            ('CECO Environmental Corp.', 'ante', 4.53, false, 'HabitassePlatea.mp3', 2, 8),
            ('Epizyme, Inc.', 'cum', 1.11, false, 'CrasMiPede.tiff', 2, 90),
            ('Protective Life Corporation', 'adipiscing molestie hendrerit at vulputate', 9.87, false, 'Penatibus.gif', 3, 56),
            ('Dominion Energy Midstream Partners, LP', 'ut rhoncus aliquet pulvinar sed', 7.66, true, 'Sapien.png', 3, 71),
            ('MSB Financial Corp.', 'nunc vestibulum', 1.59, true, 'IntegerPedeJusto.jpeg', 2, 71),
            ('Citigroup Inc.', 'hendrerit at vulputate', 3.47, false, 'MolestieNibhIn.mov', 1, 68),
            ('Boulevard Acquisition Corp. II', 'non', 7.57, true, 'EuFelis.doc', 1, 100),
            ('Biomerica, Inc.', 'eget eleifend', 1.46, true, 'ConvallisNunc.ppt', 2, 43),
            ('Whirlpool Corporation', 'neque vestibulum', 5.28, false, 'Faucibus.mp3', 1, 84);
        ";

        $db->exec($query);
    }
}